# Generated by Django 5.2.5 on 2026-04-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field4', models.EmailField(max_length=254)),
                ('field5', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField()),
                ('field2', models.IntegerField()),
                ('field3', models.CharField(max_length=10)),
            ],
        ),
    ]
