# Generated by Django 5.2.5 on 2026-04-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='field1',
            field=models.CharField(max_length=100),
        ),
    ]
