# Generated by Django 5.2.5 on 2026-04-20 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_core_field1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Components',
            new_name='Component',
        ),
    ]
