# Generated by Django 5.2.5 on 2026-04-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_components_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='field4',
            field=models.IntegerField(),
        ),
    ]
