# Generated by Django 5.2.5 on 2026-04-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_component_field4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field6', models.IntegerField()),
                ('field7', models.CharField(max_length=128)),
            ],
        ),
    ]
