# Generated by Django 5.2.5 on 2026-04-21 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
