# Generated by Django 5.2.5 on 2026-04-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_items_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Generic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field8', models.IntegerField()),
                ('field9', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Viewset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field10', models.IntegerField()),
                ('field11', models.CharField(max_length=128)),
            ],
        ),
    ]
