# Generated by Django 5.2.5 on 2026-04-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_item_generic_item_viewset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_ViewsetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field12', models.IntegerField()),
                ('field13', models.CharField(max_length=128)),
            ],
        ),
    ]
