# Generated by Django 5.2.5 on 2026-04-23 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_item_viewsetmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abuzar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Abuzar1', models.CharField(max_length=10)),
                ('Abuzar2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Owais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owais1', models.CharField(max_length=10)),
                ('Owais2', models.IntegerField()),
                ('owais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OWAIS', to='api.abuzar')),
            ],
        ),
    ]
