# Generated by Django 5.2.5 on 2026-04-24 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_abuzar_owais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owais',
            old_name='owais',
            new_name='abuzar',
        ),
    ]
