# Generated by Django 5.2.5 on 2026-07-09 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_owais_owais_abuzar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owais',
            name='abuzar',
        ),
        migrations.DeleteModel(
            name='Abuzar',
        ),
        migrations.DeleteModel(
            name='Owais',
        ),
    ]
