# Generated by Django 5.2.5 on 2026-07-10 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('dayDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='destinationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyager.daymodel')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.city')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('day', 'destination')},
            },
        ),
        migrations.AddField(
            model_name='daymodel',
            name='destinations',
            field=models.ManyToManyField(through='voyager.destinationModel', to='cities_light.city'),
        ),
        migrations.CreateModel(
            name='TripsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=100)),
                ('description', models.TextField(blank=True, max_length=512)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='daymodel',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyager.tripsmodel'),
        ),
    ]
